name: Build ThunderOnWindows

# CHANGE TO MASTER
on:
  push:
    branches: ["development/actions"]
  pull_request:
    branches: ["master"]
 
# CHANGE TO RDKCENTRAL
# CHANGE TO MASTER
jobs:
  ThunderClientLibraries:
    uses: VeithMetro/Thunder/.github/workflows/Build Thunder on Windows.yml@development/actions-thunderonwindows
