name: Build ThunderOnWindows

# CHANGE TO MASTER
on:
  push:
    branches: ["development/actions"]
  pull_request:
    branches: ["master"]
 
jobs:
  ThunderClientLibraries:
    uses: rdkcentral/Thunder/.github/workflows/Build Thunder on Windows.yml@master
