name: Build ThunderOnWindows

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
 
env:
  devEnv: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
  solution: Thunder.sln

jobs:
  ThunderOnWindows:
    runs-on: windows-latest

    strategy:
      matrix:
        type: [Debug]
        version: [64]

    name: Build type - ${{matrix.type}}${{matrix.version}}
    steps:
    - name: Checkout ThunderOnWindows
      uses: actions/checkout@v3
      with:
        path: ThunderOnWindows
        repository: WebPlatformForEmbedded/ThunderOnWindows

    - name: Checkout Thunder
      uses: actions/checkout@v3
      with:
        ref: R2
        path: ThunderOnWindows/Thunder
        repository: rdkcentral/Thunder

    - name: Install jsonref
      run: pip install jsonref

    - name: Build ThunderOnWindows
      shell: cmd
      run: |
        cd ThunderOnWindows
        "%devEnv%" /Build "${{matrix.type}}|x${{matrix.version}}"  "%solution%"
        
    - name: Tar files
      run: tar -czvf ${{matrix.type}}${{matrix.version}}.tar.gz artifacts
    
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Thunder-${{matrix.type}}${{matrix.version}}-artifact
        path: ${{matrix.type}}${{matrix.version}}.tar.gz
